// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkyehtnlfywgfrpvbahy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpreWVodG5sZnl3Z2ZycHZiYWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Njg4MTQsImV4cCI6MjA2MTA0NDgxNH0.e3UCda3c6ZG7nmeni78QGgTV0LSXJDGKdKXnp9qoBCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);